name: GPU Testing Workflow on HDFML machine

on: push

jobs:
  submit-gpu-tests:
    name: Submit GPU test batch job
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HDFML_HOST }}
          username: ${{ secrets.HDFML_NAME }}
          key: ${{ secrets.HDFML_KEY }}
          envs: GITHUB_SHA
          script: |
            mkdir tmp
            cd tmp
            git clone https://github.com/helmholtz-analytics/heat.git
            cd  heat
            git fetch
            git checkout $GITHUB_SHA
            {
              echo -n -e "#!/bin/bash -x\n";
              echo -n -e "#SBATCH --acount=haf --nodes=4 --ntasks-per-node=2 --cpus-per-task=1 --time=00:05:00\n";
              cat .github/workflows/gpu_test_template.sh;
            } > test_batch_script.sh
            cat test_batch_script.sh
            export SHA=$GITHUB_SHA
            export NUM_PROC=8
            sbatch test_batch_script.sh
