name: GPU Testing Workflow on HDFML machine

on:
  push:
    branches:
      - gpu-test-automation

jobs:
  run-gpu-tests:
    name: run tests on gpu
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HDFML_HOST }}
          username: ${{ secrets.HDFML_NAME }}
          key: ${{ secrets.HDFML_KEY }}
          envs: STATUS_TOKEN,GITHUB_REF,GITHUB_SHA
          script: |
            curl -H "Content-Type: application/json" -H "Authorization: token $STATUS_TOKEN" -X POST -d '{"state": "pending", "description": "GPU Test Status", "context": "continuous-integration/gpu"}' https://api.github.com/repos/helmholtz-analytics/heat/statuses/$GITHUB_SHA
            source .virtualenvs/heat/bin/activate
            cd heat
            git fetch
            git checkout $GITHUB_REF
            module load Python/3.6.8
            module load GCC
            module load Intel
            module load ParaStationMPI
            python -m pip install --user codecov pytest coverage
            python -m pip install --user -e .
            python -m coverage run --source=heat -m pytest
            python -m coverage report
            curl -H "Content-Type: application/json" -H "Authorization: token $STATUS_TOKEN" -X POST -d '{"state": "success", "description": "GPU Test Status", "context": "continuous-integration/gpu"}' https://api.github.com/repos/helmholtz-analytics/heat/statuses/$GITHUB_SHA
