name: GPU Testing Workflow on HDFML machine

on:
  push:
    branches:
      - gpu-test-automation

jobs:
  run-gpu-tests:
    name: run tests on gpu
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HDFML_HOST }}
          username: ${{ secrets.HDFML_NAME }}
          key: ${{ secrets.HDFML_KEY }}
          script: |
            source .virtualenvs/heat/bin/activate
            cd heat
            git fetch
            git checkout $GITHUB_REF
            module load Python/3.6.8
            module load GCC
            module load Intel
            module load ParaStationMPI
            python -m pip install codecov pytest coverage
            python -m pip install -e .
            python -m coverage run --source=heat -m pytest
            coverage combine
            coverage report
