name: GPU Testing Workflow on HDFML machine

on: push

jobs:
  submit-gpu-tests:
    name: Submit GPU test batch job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        processes: [1, 2, 3]
        gpus: [1, 2, 3, 4]
        exclude:
          - processes: 2
            gpus: 1
          - processes: 2
            gpus: 2
          - processes: 2
            gpus: 3
          - processes: 3
            gpus: 1
          - processes: 3
            gpus: 2
          - processes: 3
            gpus: 3
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HDFML_HOST }}
          username: ${{ secrets.HDFML_NAME }}
          key: ${{ secrets.HDFML_KEY }}
          envs: GITHUB_SHA
          script: |
            mkdir tmp
            cd tmp
            git clone https://github.com/helmholtz-analytics/heat.git
            cd  heat
            git fetch
            git checkout $GITHUB_SHA
            {
              echo -n -e "#!/bin/bash -x\n";
              echo -n -e "#SBATCH --account=haf --nodes=2 --ntasks-per-node=1 --cpus-per-task=1 --time=00:05:00 --gres=gpu:${{ matrix.gpus }}\n";
              cat .github/workflows/gpu_test_template.sh;
            } > test_batch_script.sh
            cat test_batch_script.sh
            export SHA=$GITHUB_SHA
            sbatch test_batch_script.sh ${{ matrix.processes }}
